# fly.toml app configuration file generated for cn-test on 2023-05-09T15:02:18-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cn-test"
primary_region = "ord"

[http_service]
  internal_port = 5173
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
